### ISSUE TITLE
Feature Request: Direct loading of model skipping selecting file

### ISSUE THREAD

**Issue by bmsleight** [jschobben/modelview#1]
Hi - I am using ColorSCAD and now have a great colored model from my OpenSCAD model 

I like to host this my own webpage - but I do quite get javascript. Is there a simple way I can edit index.htm so it loads the model.3mf directly (on same webserver) - without the use having to browse to the file  ?

**Comment by jschobben** [comment]
Yes indeed, this deserves a proper example. I added one just now (single_file.htm), see if it fits your purpose.

**Comment by bmsleight** [comment]
Perfect - thanks you very much, works excellent.  
I owe you a beer/coffee!
